version: '3.7'

services:
  # db:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - user-coordinate-data:/data/db
  #   networks:
  #     - pathage-net

  server:
    image: pathage-server
    container_name: server
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - pathage-net
    # depends_on:
    #   - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  nginx:
    build:
      context: ./nginx
    ports:
      - 81:80
    depends_on:
      - server
    networks:
      - pathage-net

# volumes:
#   user-coordinate-data:
  
networks:
  pathage-net:
    driver: bridge
